services:
  api_chatbot:
    build: .
    container_name: api_chatbot
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    # Si quieres desarrollar con hot-reload, descomenta las siguientes l√≠neas:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # command: npm run dev
